server:
  port: 8080

spring:
  application:
    name: spring-security-oauth2-server
  datasource:
    type: com.zaxxer.hikari.util.DriverDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/oauth2_server?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: cn.tellsea.oauth2.server.bean
  mapper-locations: classpath:mapper/*.xml
